### ISSUE TITLE
BRT lesson title, timing not showing up on schedule

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/2021-04-13-act-workshop#23]
Anyone have any clues as to why the BRT section isn't showing up?

**Comment by jdpye** [comment]
I tried to fix it and made it worse, now the intro actel title has disappeared as well. Seeking some backup on this one.

**Comment by jackVanish** [comment]
Formatting in the markdown at the top of the page was off, causing the pages to build improperly. The BRT section had spaces instead of tabs in some of the indentations for questions/objectives, and the Actel one was missing dashes and quotes for its questions. Fixing those made the titles show up.
