### ISSUE TITLE
update c.bangley sections 

### ISSUE THREAD

**Issue by naomitress** [ocean-tracking-network/2021-04-13-act-workshop#5]
when ready these are the places to update:

- https://github.com/ocean-tracking-network/2021-04-13-act-workshop/blob/gh-pages/Resources/Bangley%20FACT%20BRT%20Analysis.pptx

- https://github.com/ocean-tracking-network/2021-04-13-act-workshop/tree/gh-pages/_episodes  (if the file name or content highlights change)

**Comment by jdpye** [comment]
New versions are committed by @ChuckBangley , we are good to go in gh-pages to link to their new versions in the Resources subfolder

**Comment by naomitress** [comment]
doing it here https://github.com/ocean-tracking-network/2021-04-13-act-workshop/pull/9

**Comment by naomitress** [comment]
all done
